spectech/spectech/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from tracker.views import CustomLoginView

from tracker.views import get_build_objects

from tracker.views import special_equipment_info

urlpatterns = [
    path('admin/', admin.site.urls),
    path('rental/', include('tracker.urls')),
    path('login/', CustomLoginView.as_view(), name='login'),
    path('', RedirectView.as_view(url='/rental/calendar/')),
    path('get_build_objects/', get_build_objects, name='get_build_objects'),
    path('rental_report/', special_equipment_info, name='special_equipment_info')
]

spectech/tracker/urls.py
from django.urls import path

from .services import upload_documents
from .views import RentalCalendarView, RentalDetailView, RentalDeleteView, CarListView, CarDetailView, ClientListView, \
    ShiftCreateView, RentalListView, logout_view, ClientDetailView

urlpatterns = [
    path('calendar/', RentalCalendarView.as_view(), name='rental_calendar'),
    path('info/<int:pk>/', RentalDetailView.as_view(), name='rental_detail'),
    path('rental/info/<int:pk>/add_shift/', ShiftCreateView.as_view(), name='add_shift'),
    path('create/', RentalCalendarView.as_view(), name='rental_create'),
    path('delete/<int:pk>/', RentalDeleteView.as_view(), name='rental_delete'),
    path('list/cars', CarListView.as_view(), name='car_list'),
    path('list/cars/<int:pk>/', CarDetailView.as_view(), name='car_detail'),
    path('list/clients', ClientListView.as_view(), name='client_list'),
    path('list/clients/<int:pk>/', ClientDetailView.as_view(), name='client_detail'),
    path('list/rentals', RentalListView.as_view(), name='rental_list'),
    path('logout/', logout_view, name='logout'),
    path('rental/upload_documents/<int:pk>/', upload_documents, name='upload_documents'),
]

spectech/tracker/models.py
from dateutil.relativedelta import relativedelta
from django.contrib.auth import get_user_model
from django.db import models
from django.utils import timezone
from polymorphic.models import PolymorphicModel
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django_redis import get_redis_connection

User = get_user_model()
#TODO: поправить овнера
#TODO: добавить свободный файл в загрузку
#TODO: добавить несколько документов одного типа


# Модель для хранения информации о владельце техники
class Owner(models.Model):
    owner_type = models.CharField('Тип владельца', max_length=20)
    name = models.CharField('Наименование', max_length=20)
    inn = models.CharField('ИНН', max_length=20)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Владельца'
        verbose_name_plural = 'Владельцы'


# Модель для хранения информации о типе техники
class CarType(models.Model):
    name = models.CharField('Наименование', max_length=100)

    class Meta:
        verbose_name = 'Тип техники'
        verbose_name_plural = 'Тип техники'

    def __str__(self):
        return self.name


# Модель для хранения информации о лизинге
class Leasing(models.Model):
    bank = models.CharField('Банк', max_length=100)
    amount = models.DecimalField('Сумма', max_digits=10, decimal_places=2)
    term = models.IntegerField('Срок')
    monthly_payment_date = models.PositiveIntegerField('Дата ежемесячного погашения')

    class Meta:
        verbose_name = 'Лизинг'
        verbose_name_plural = 'Лизинг'

    def __str__(self):
        return f"{self.bank} - {self.amount}"


# Модель для хранения информации о страховке
class Insurance(models.Model):
    osago_number = models.CharField('Номер ОСАГО', max_length=100, blank=True, null=True)
    osago_expiry_date = models.DateField('Действует до (ОСАГО)', blank=True, null=True)
    kasko_number = models.CharField('Номер КАСКО', max_length=100, blank=True, null=True)
    kasko_expiry_date = models.DateField('Действует до (КАСКО)', blank=True, null=True)
    car = models.ForeignKey('Car', verbose_name='Техника', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Страховка'
        verbose_name_plural = 'Страховки'


# Модель для хранения информации о технике
class Car(models.Model):
    name = models.CharField('Наименование', max_length=100)
    model = models.CharField('Модель', max_length=100)
    number = models.CharField('Номер', max_length=9)
    start_date = models.DateField('Дата начала', default=timezone.now)
    end_date = models.DateField('Дата окончания', blank=True, null=True)
    price = models.IntegerField('Цена')
    owner = models.ForeignKey(Owner, verbose_name='Владелец', on_delete=models.CASCADE)
    fuel_consumption = models.DecimalField('Расход топлива', max_digits=10, decimal_places=2)
    leasing = models.OneToOneField(Leasing, verbose_name='Лизинг', blank=True, null=True, on_delete=models.SET_NULL)
    car_type = models.ForeignKey(CarType, verbose_name='Тип техники', on_delete=models.CASCADE)
    work_mode = models.CharField(verbose_name='Доп. режим работы', blank=True, null=True, max_length=5)

    # Дополнительные поля
    year_of_manufacture = models.PositiveIntegerField('Год выпуска', blank=True, null=True)
    vin = models.CharField('VIN', max_length=17, blank=True, null=True)
    chassis_number = models.CharField('Номер шасси', max_length=100, blank=True, null=True)
    body_number = models.CharField('Номер кузова', max_length=100, blank=True, null=True)
    engine_number = models.CharField('Номер двигателя', max_length=100, blank=True, null=True)
    engine_volume = models.CharField('Объем', max_length=50, blank=True, null=True)
    fuel_type = models.CharField('Тип топлива', max_length=50, blank=True, null=True)
    fuel_card_number = models.CharField('Номер топливной карты', max_length=50, blank=True, null=True)
    inspection_number = models.CharField('Номер ТО', max_length=50, blank=True, null=True)
    inspection_expiry_date = models.DateField('Срок действия ТО', blank=True, null=True)

    class Meta:
        verbose_name = 'Технику'
        verbose_name_plural = 'Техника'

    def __str__(self):
        return f"{self.car_type.name} - {self.number}"


# Модель для хранения информации о рабочих-операторах
class Worker(models.Model):
    full_name = models.CharField('Полное имя', max_length=50)
    mobile_numer = models.CharField('Мобильный номер', max_length=50)
    hourly_rate = models.DecimalField('Почасовая ставка', max_digits=10, decimal_places=2)
    passport = models.CharField('Паспорт', max_length=50)

    class Meta:
        verbose_name = 'Оператора'
        verbose_name_plural = 'Операторы'

    def __str__(self):
        return self.full_name


# Модель для хранения информации об объектах строительства
class BuildObject(models.Model):
    name = models.CharField('Название объекта', max_length=100)
    address = models.CharField('Адрес объекта', max_length=200)
    client = models.ForeignKey('Client', verbose_name='Клиент', on_delete=models.CASCADE)

    class Meta:
        verbose_name = 'Объект'
        verbose_name_plural = 'Объекты'

    def __str__(self):
        return self.name


# Модель для хранения информации о клиентах
class Client(PolymorphicModel):
    name = models.CharField('Имя/Название огранизации', max_length=50)
    email = models.EmailField('Email')
    phone = models.CharField('Телефон', max_length=15)

    # Поля для реализации полиморфизма
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, editable=False, null=True)
    object_id = models.PositiveIntegerField(editable=False, null=True)
    content_object = GenericForeignKey('content_type', 'object_id')

    class Meta:
        verbose_name = 'Клиент'
        verbose_name_plural = 'Клиенты'

    def __str__(self):
        return f"{self.name} - {self.get_client_type()}"

    # Метод для получения типа клиента
    def get_client_type(self):
        return self.content_type

    get_client_type.short_description = 'Тип клиента'

    def save(self, *args, **kwargs):
        # Перед сохранением объекта, устанавливаем соответствующие значения для content_type и object_id
        self.content_type = ContentType.objects.get_for_model(self)
        self.object_id = self.id
        super().save(*args, **kwargs)


# Модель для хранения информации о физических лицах
class IndividualClient(Client):
    passport = models.CharField('Паспорт', max_length=12)

    class Meta:
        verbose_name = 'Физическое лицо'
        verbose_name_plural = 'Физические лица'

    def __str__(self):
        return f"{self.name} "

    def get_client_type(self):
        return "Физическое лицо"


# Модель для хранения информации о юридических лицах
class LegalClient(Client):
    reprasintative_name = models.CharField('Имя представителя', max_length=100)
    vat_number = models.CharField('ИНН', max_length=20)

    class Meta:
        verbose_name = 'Юридическое лицо'
        verbose_name_plural = 'Юридические лица'

    def __str__(self):
        return self.name

    def get_client_type(self):
        return "Юридическое лицо"


# Модель для хранения информации об аренде
class Rental(models.Model):
    client = models.ForeignKey(Client, verbose_name='Клиент', on_delete=models.CASCADE)
    car = models.ForeignKey(Car, verbose_name='Техника', on_delete=models.CASCADE)
    start_date = models.DateField('Дата начала')
    end_date = models.DateField('Дата окончания')
    manager = models.ForeignKey(User, verbose_name='Менеджер', on_delete=models.CASCADE)
    build_object = models.ForeignKey(BuildObject, verbose_name='Объект', on_delete=models.CASCADE, blank=True, null=True)
    tariff = models.IntegerField('Цена(час)', blank=True, null=True)
    extra_tariff = models.IntegerField('Цена(доп.режим работы)', blank=True, null=True)

    contract_file = models.FileField(verbose_name='Договор', upload_to='rental_files/', null=True, blank=True)
    invoice_file = models.FileField(verbose_name='Счет', upload_to='rental_files/', null=True, blank=True)
    upd_file = models.FileField(verbose_name='УПД', upload_to='rental_files/', null=True, blank=True)
    esm7_file = models.FileField(verbose_name='ЭСМ-7', upload_to='rental_files/', null=True, blank=True)
    waybill_file = models.FileField(verbose_name='Путевой лист', upload_to='rental_files/', null=True, blank=True)

    class Meta:
        verbose_name = 'Аренду'
        verbose_name_plural = 'Аренды'

    def __str__(self):
        return f'{self.start_date},{self.end_date}'

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.clear_cache()

    def delete(self, *args, **kwargs):
        super().delete(*args, **kwargs)
        self.clear_cache()

    # Метод для очистки кэша
    def clear_cache(self):
        redis_conn = get_redis_connection()
        current_date = self.start_date
        while current_date <= self.end_date:
            cache_key = f"rental_calendar_{current_date.strftime('%Y-%m')}"
            redis_conn.delete(cache_key)
            current_date += relativedelta(months=1)


# Модель для хранения информации о сменах
class Shift(models.Model):
    worker = models.ForeignKey(Worker, verbose_name='Рабочий', on_delete=models.CASCADE)
    date = models.DateField()  # Добавляем поле даты
    start_time = models.TimeField(verbose_name='Время начала')  # Поле времени начала
    end_time = models.TimeField(verbose_name='Время окончания')  # Поле времени окончания
    rental = models.ForeignKey(Rental, related_name='shifts', verbose_name='Аренда', on_delete=models.CASCADE)
    is_additional_mode = models.BooleanField('Дополнительный режим', default=False)
    dinner = models.BooleanField('Обед', default=False)

    def __str__(self):
        return f"Смена {self.worker}"

    class Meta:
        verbose_name = 'Смену'
        verbose_name_plural = 'Смены'

spectech/tracker/forms.py
from django import forms
from django.forms import formset_factory
from django.utils import timezone

from .models import Rental, Shift


class ShiftForm(forms.ModelForm):
    class Meta:
        model = Shift
        fields = ('worker', 'date', 'start_time', 'end_time', 'dinner', 'is_additional_mode')
        widgets = {
            'date': forms.DateInput(attrs={'type': 'date'}),
            'start_time': forms.TimeInput(attrs={'type': 'time'}),
            'end_time': forms.TimeInput(attrs={'type': 'time'}),
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        instance = kwargs.get('instance')
        if instance and instance.rental:
            rental = instance.rental
            self.fields['date'].widget.attrs['min'] = rental.start_date.strftime('%Y-%m-%d')
            self.fields['date'].widget.attrs['max'] = rental.end_date.strftime('%Y-%m-%d')


class RentalForm(forms.ModelForm):
    class Meta:
        model = Rental
        fields = ['client', 'car', 'start_date', 'end_date', 'manager', 'build_object', 'tariff', 'extra_tariff']
        labels = {
            'client': 'Клиент',
            'car': 'Техника',
            'start_date': 'Дата начала',
            'end_date': 'Дата окончания',
            'build_object': 'объект',
            'tariff': 'Цена',
            'extra_tariff': 'Цена за дополнительный режим'
        }
        widgets = {
            'start_date': forms.DateInput(attrs={'type': 'date'}),
            'end_date': forms.DateInput(attrs={'type': 'date'}),
        }


class DocumentForm(forms.Form):
    contract_file = forms.FileField(required=False)
    invoice_file = forms.FileField(required=False)
    upd_file = forms.FileField(required=False)
    esm7_file = forms.FileField(required=False)
    waybill_file = forms.FileField(required=False)

spectech/tracker/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <title>SpecTech</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

</head>
<body>
{% if user.is_authenticated %}
<nav class="navbar navbar-expand-lg navbar-dark">
    <a class="navbar-brand" href="#">SpecTech</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rental_calendar'%}">Календарь</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'special_equipment_info'%}">Отчет</a>
            </li>
           <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown"
       aria-haspopup="true" aria-expanded="false">
        Списки
    </a>
    <div class="dropdown-menu animate__animated animate__fade" aria-labelledby="navbarDropdown1">
        <a class="dropdown-item" href="{% url 'car_list'%}">Техника</a>
        <a class="dropdown-item" href="{% url 'client_list'%}">Заказчики</a>
        <a class="dropdown-item" href="{% url 'rental_list'%}">Аренды</a>
    </div>
</li>
        </ul>
        {% if user.is_authenticated %}
        <ul class="navbar-nav ml-auto">
            {% if user.is_superuser %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'admin:index' %}">Админка</a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Выход</a>
            </li>
        </ul>
        {% endif %}
    </div>
</nav>
{% endif %}
<div class="container">
    {% block content %}
    {% endblock %}
</div>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

spectech/tracker/templates/login.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card shadow animate__animated animate__fadeInDown">
        <div class="card-header bg-dark text-white">
          <h3 class="card-title">Вход</h3>
        </div>
        <div class="card-body">
          <form method="post" class="d-flex flex-column align-items-center" id="loginForm">
            {% csrf_token %}
            <div class="form-group w-100">
              <label for="{{ form.username.id_for_label }}">Логин</label>
              {{ form.username }}
            </div>
            <div class="form-group w-100">
              <label for="{{ form.password.id_for_label }}">Пароль</label>
              {{ form.password }}
            </div>
            <button type="submit" class="btn btn-secondary">Войти</button> <!-- Заменяем "btn-primary" на "btn-secondary" -->
          </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Подключаем библиотеку animate.css -->
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css">

<script>
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('loginForm');
    form.classList.add('animate__animated', 'animate__fadeInDown');
  });
</script>
{% endblock %}

spectech/tracker/templates/rental_calendar.html
{% extends 'base.html' %}
{% block content %}
    <h1>Календарь аренд</h1>

    <div id="month-selection">
        <form method="get" action="{% url 'rental_calendar' %}">
            <div class="form-group row">
                <label for="month" class="col-sm-2 col-form-label">Выберите месяц:</label>
                <div class="col-sm-4">
                    <input type="month" id="month" name="month" class="form-control" value="{{ selected_month }}" required>
                </div>
                <div class="col-sm-6">
                    <button type="submit" class="btn btn-primary">Показать</button>
                </div>
            </div>
        </form>
    </div>
<div id="calendar-container" style="overflow-x: scroll;">
    <table class="table table-bordered table-striped" style="min-width: 100%; table-layout: fixed;">
        <thead>
            <tr>
                <th style="width: 100px;">Car</th>
                {% for date in dates %}
                    <th style="width: 100px;">{{ date }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for car_name, rentals in booked_dates.items %}
                <tr>
                    <td class="fixed-column">{{ car_name }}</td>
                    {% for dat in dates %}
                        {% if dat in rentals|join:", " %}
                            <td class="booked">
                                {% for rental in rentals %}
                                    {% for key, value in rental.items %}
                                        {% if dat in value.1 %}
                                            <a href="{% url 'rental_detail' key %}" class="text-light">{{ value.0 }}</a>
                                            <a href="{% url 'rental_delete' key %}" class="delete-rental" style="float: right;">
                                                <i class="fa fa-trash text-light"></i>
                                            </a>
                                        {% endif %}
                                    {% endfor %}
                                {% endfor %}
                            </td>
                        {% else %}
                            <td style="width: 100px;"></td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>


<div id="create-rental-form" style="margin-top: 20px;">
    <h2>Добавить аренду</h2>
    <form method="post" action="{% url 'rental_create' %}">
        {% csrf_token %}
        <div class="form-group row">
            <label for="car" class="col-md-2 col-form-label">Техника:</label>
            <div class="col-md-4">
                {{ form.car }}
                {% if form.car.errors %}
                    <div class="invalid-feedback">
                        {{ form.car.errors }}
                    </div>
                {% endif %}
            </div>
            <label for="manager" class="col-md-2 col-form-label">Менеджер:</label>
            <div class="col-md-4">
                {{ form.manager }}
                {% if form.manager.errors %}
                    <div class="invalid-feedback">
                        {{ form.manager.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="client" class="col-md-2 col-form-label">Клиент:</label>
            <div class="col-md-4">
                {{ form.client }}
            </div>
            <label for="build_object" class="col-md-2 col-form-label">Объект:</label>
            <div class="col-md-4">
                <select name="build_object" id="id_build_object" class="form-control" style="height: auto;">
                </select>
            </div>
        </div>
        <div class="form-group row">
            <label for="tariff" class="col-md-2 col-form-label">Тариф:</label>
            <div class="col-md-4">
                {{ form.tariff }}
                {% if form.tariff.errors %}
                    <div class="invalid-feedback">
                        {{ form.tariff.errors }}
                    </div>
                {% endif %}
            </div>
            <label for="extra_tariff" class="col-md-2 col-form-label">Доп. тариф:</label>
            <div class="col-md-4">
                {{ form.extra_tariff }}
                {% if form.extra_tariff.errors %}
                    <div class="invalid-feedback">
                        {{ form.extra_tariff.errors }}
                    </div>
                {% endif %}
            </div>
        </div>
        <div class="form-group row">
            <label for="start_date" class="col-md-2 col-form-label">Дата начала:</label>
            <div class="col-md-4">
                {{ form.start_date }}
                {% if form.start_date.errors %}
                    <div class="invalid-feedback">
                        {{ form.start_date.errors }}
                    </div>
                {% endif %}
            </div>
            <label for="end_date" class="col-md-2 col-form-label">Дата окончания:</label>
            <div class="col-md-4">
                {{ form.end_date }}
                {% if form.end_date.errors %}
                    <div class="invalid-feedback">
                        {{ form.end_date.errors }}
                    </div>
                {% endif %}
            </div>
        </div>

        <div class="form-group row">
            <div class="col-md-10 offset-md-2">
                <button type="submit" class="btn btn-primary">Создать</button>
            </div>
        </div>
    </form>
</div>


    <script>
        // Обработчик события для удаления аренды
        const deleteLinks = document.getElementsByClassName('delete-rental');
        for (const link of deleteLinks) {
            link.addEventListener('click', function (event) {
                event.preventDefault();
                if (confirm('Вы уверены, что хотите удалить эту аренду?')) {
                    const url = this.getAttribute('href');
                    const rentalId = this.getAttribute('data-rental-id');  // Получаем идентификатор аренды
                    fetch(url, {
                        method: 'POST',
                        headers: {
                            'Content-Type': 'application/json',
                            'X-CSRFToken': '{{ csrf_token }}'
                        },
                        body: JSON.stringify({ rental_id: rentalId })  // Передаем идентификатор аренды в теле запроса
                    })
                    .then(response => {
                        if (response.ok) {
                            location.reload();  // Перезагрузка страницы после успешного удаления
                        } else {
                            console.error('Ошибка при удалении аренды');
                        }
                    })
                    .catch(error => {
                        console.error('Ошибка при удалении аренды:', error);
                    });
                }
            });
        }
    </script>
 <script>
    document.addEventListener("DOMContentLoaded", function () {
        // Найдем элемент ленты
        const calendarContainer = document.getElementById("calendar-container");
        if (!calendarContainer) {
            console.error("Элемент #calendar-container не найден.");
            return;
        }

        // Получим текущую дату
        const currentDate = new Date();
        const currentYear = currentDate.getFullYear();
        const currentMonth = currentDate.getMonth();
        const currentDay = currentDate.getDate()

        // Найдем элемент с текущей датой внутри ленты
        const currentDayElement = calendarContainer.querySelector(
            `th:nth-child(${currentDay })`
        );
        if (!currentDayElement) {
            console.error("Элемент текущего месяца не найден.");
            return;
        }

        // Посчитаем ширину элементов до текущего месяца и прокрутим ленту
        const scrollPosition = currentDayElement.offsetLeft;
        calendarContainer.scrollLeft = scrollPosition;
    });
</script>
<script>
    document.getElementById('id_client').addEventListener('change', function () {
        var clientId = this.value;
        var buildObjectField = document.getElementById('id_build_object');
        buildObjectField.innerHTML = '';

        fetch(`/get_build_objects/?client_id=${clientId}`)
            .then(response => response.json())
            .then(data => {
                data.forEach(obj => {
                    var option = document.createElement('option');
                    option.value = obj.id;
                    option.textContent = obj.name + ' - ' + obj.address;
                    buildObjectField.appendChild(option);
                });
            });
    });
</script>

{% endblock %}

spectech/tracker/templates/special_equipment_info.html
{% extends "base.html" %}

{% block title %}Генерация отчета{% endblock %}

{% block content %}
<h1>Отчет по арендам</h1>
<form method="POST" action="{% url 'special_equipment_info' %}">
    {% csrf_token %}
    <div class="form-group">
        <label for="selected_month">Выберите месяц:</label>
        <input type="month" id="selected_month" name="selected_month" value="{{ selected_month }}" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Загрузить подробный отчет</button>
</form>
{% endblock %}